## File input/output: scipy.io

In [6]:
import numpy as np
from scipy import io as spio
a = np.ones((3, 3))
spio.savemat('file.mat', {'a':a})
data = spio.loadmat('file.mat', struct_as_record= True)
data['a']


array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [11]:
from scipy import misc
misc.imread('red_elephant.png')
import matplotlib.pyplot as plt
plt.imread('red_elephant.png')
plt.imshow(misc.imread('red_elephant.png'))

- Text files: numpy.loadtxt() /numpy.savetxt()
- text/csv: numpy.genfromtxt() / numpy.recfromcsv()
- numpy-specific, binary format: numpy.save()/ numpy.load()

## Special functions: scipy.special
- Besel function: `scipy.special.jn()` (nth integer order Besel function)
- Elliptic function: `scipy.special.ellipj()` (Jacobian elliptic function)
- Gamma function: `scipy.special.gamma()`, `scipy.special.gammaln()`
- Erf, the era under a Gaussian curve: `scipy.special.erf()`

## Linear algebra operations: `scipy.linalg`

#### determinant

In [16]:
from scipy import linalg
arr = np.array([[1, 2], 
               [3, 4]])
linalg.det(arr)

-2.0

In [17]:
linalg.det(np.ones((3,3)))

0.0

In [15]:
linalg.det(np.eye(5))

1.0

#### inverse

In [19]:
arr = np.array([[1,2], 
                [3,4]])
iarr = linalg.inv(arr)
iarr

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [22]:
# computing the inverse of a singular matrix (its determinant is zero) will raise LinAlgError 
np.allclose(np.dot(arr, iarr), np.eye(2))

True

In [23]:
arr = np.arange(9).reshape((3,3)) + np.diag([1,0,1])
uarr, spec, vharr = linalg.svd(arr)

In [24]:
spec

array([ 14.88982544,   0.45294236,   0.29654967])

In [26]:
sarr = np.diag(spec)
svd_mat = uarr.dot(sarr).dot(vharr)
np.allclose(svd_mat, arr)

True

## Fast Fouier transforms: `scipy.fftpack`

In [27]:
time_step = 0.02
period = 5.
time_vec = np.arange(0, 20, time_step)
sig = np.sin(2 * np.pi /period * time_vec) + \
    0.5 * np.random.randn(time_vec.size)

In [33]:
from scipy import fftpack
sample_freq = fftpack.fftfreq(sig.size, d=time_step)
sig_fft = fftpack.fft(sig)
pidxs = np.where(sample_freq > 0)
freqs = sample_freq[pidxs]
power = np.abs(sig_ftt)[pidxs]

In [34]:
freq = freqs[power.argmax()]
np.allclose(freq, 1./period)

True

In [38]:
sig_fft[np.abs(sample_freq) > freq] = 0
main_sig = fftpack.fft(sig_fft)
import pylab as plt
plt.figure()
plt.plot(time_vec, sig)
plt.plot(time_vec, main_sig, linewidth=3)
plt.xlabel('Time [s]')
plt.ylabel('Amplitude')


C:\Users\Chao\Anaconda3\lib\site-packages\numpy\core\numeric.py:474: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)


## Statistics and random numbers: `scipy.stats`

## Interpolation: `scipy.interplate`

## Numerical integration: `scipy.integrate`

## signal processing: `scipy.signal`

## Image processing: `scipy.ndimage`

## Summary exercises on scientific computing